import type { Contractor } from "../state/types";

/* "Download CV" has no real file behind it in the prototype, so rather than a
   toast that claims a download happened, it hands over a plain-text stub built
   from what the pool actually knows about the contractor. */

export function downloadCv(c: Contractor): string {
  const name = c.name || "Contractor";
  const lines = [
    name,
    c.role ?? "Role not set",
    "",
    `Email: ${c.email ?? "—"}`,
    `Experience: ${c.seniority ?? "—"}`,
    `Working from: ${c.location ?? "—"}`,
    `Rate: ${c.rate ?? "—"}`,
    `Added: ${c.added} (${c.source})`,
    "",
    c.notes ? `Notes: ${c.notes}` : "",
    "",
    "Placeholder generated by the AI Scout prototype — not a real CV.",
  ];

  const fileName = `${name.replace(/[^\w\s.-]/g, "")} CV.txt`;
  const url = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/plain" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  // Revoking immediately can cancel the download in some browsers.
  setTimeout(() => URL.revokeObjectURL(url), 10_000);

  return fileName;
}
